mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls',namespace="polls")),
    # path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('submit/', views.submit, name='submit'),
    path('save_file/',views.save_file, name='save_file')
]

polls/models.py
from django.db import models

# Create your models here.

polls/forms.py
from django import forms
from django.forms import CharField, ModelMultipleChoiceField, ModelChoiceField

class LoginForm(forms.Form):
   url = forms.URLField(required=True)
   number = forms.IntegerField(required=True)
   file=forms.CharField(required=True)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from googlemaps import GoogleMapsScraper
from datetime import datetime, timedelta
import argparse
import csv
from django.urls import reverse
from polls.forms import LoginForm
import pandas as pd

HEADER = ['id_review', 'rating', 'col1', 'review', 'timestamp', 'url_user', 'time_ago', 'user_name','col2']

def index(request):

    return render(request, "polls/index.html")

def save_file(request):
	print('in save')
	fileName='attachment;filename='+file+'.csv'
	data = open('polls/mydata/gm_reviews.csv','r').read()
	resp = HttpResponse(data, content_type='application/x-download')
	resp['Content-Disposition'] = fileName
	return resp		     

def submit(request):
	global file
	MyLoginForm = LoginForm(request.POST)
	if request.method == "POST":
		if MyLoginForm.is_valid():
			number = MyLoginForm.cleaned_data['number']
			url=MyLoginForm.cleaned_data['url']
			file=MyLoginForm.cleaned_data['file']
			with GoogleMapsScraper() as scraper:
				# with open(args, 'r') as urls_file:
					# for url in urls_file:
							error = scraper.sort_by_date(url)
							if error == -1:
		                        # store reviews in CSV file
								n = 0
								rev=[]
								while n < number:
									reviews = scraper.get_reviews(n)
									rev.extend(reviews)		
									n += len(reviews)
								df = pd.DataFrame(rev)
								df.to_csv('polls/mydata/gm_reviews.csv',index=False)	
	return HttpResponseRedirect(reverse('polls:save_file'))													

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style type="text/css">
    label, .input-cell{
      width:98%;
    }
    form{
      padding:20px;
    }
    .container{
      display: table;
    margin: 0 auto;
    }
    .input-cell{
      padding: 5px;
    margin: 5px 0 10px;
    }
    label{
      font-family: sans-serif;
    }
    .submit-btn{
      margin-top:10px;
      box-sizing: unset;
    /* width: 200px; */
    /* height: 104px; */
    padding: 7px 15px !important;
    background: red;
    font-size: 16px;
    border-radius: 8px;
    color: #fff;
    font-weight: bold;
    }
    .heading{
      text-align: center;
    font-size: 25px;
    /* font-weight: bold; */
    font-family: sans-serif;
    margin: 20px 0;
    }
    form{
      background-color: #ccc;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="heading">Review scraper</div>
  <form name = "form" method="post" action="{% url 'polls:submit' %}">
  {% csrf_token %}
<label>Enter URL</label>  
<input class="input-cell" name="url" type="url">
<label>Enter no. of reviews</label>
<input class="input-cell" type="number" name="number">
<label>Enter file name</label>
<input class="input-cell" type="text" name="file">
<input class="submit-btn" type="submit" value="Submit">
</form>
<div>
</body>
</html>